language: python
python:
  - "2.6"
  - "2.7"
services: mysql
env:
  - DJANGO=1.4.5
  - DJANGO=1.5
install:
  - pip install -q mysql-python --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q South==0.7.5 --use-mirrors
  - pip install -q django-tastypie==0.9.12 --use-mirrors
  - pip install -q pycrypto==2.6 --use-mirrors
  - pip install -q markdown==2.1.1 --use-mirrors
  - pip install -q pep8 --use-mirrors
  - pip install -q pyflakes --use-mirrors
before_script:
  - "./pyflakes.sh"
  - "pep8 --exclude=migrations,lib --ignore=E501,E225,E128,E124 ."
  - mysql -e 'create database IF NOT EXISTS rattic;'
script:
  - python manage.py test
  - cp docs/travis/local_settings_mysql.py ratticweb/local_settings.py
  - python manage.py syncdb --noinput
  - python manage.py migrate
  - python manage.py test

